language: c # not go, Go runtime is managed with gvm
os: [linux, osx] # ostrost/ostent flagged multi-os
sudo: false
env:
  global:
    - UNAME="RC-`uname -sm | tr ' ' .`"
    - GVMINSTALLER_URL=https://github.com/moovweb/gvm/raw/master/binscripts/gvm-installer
  matrix:
    - GVM_GO=go1.4.2
  # - GVM_GO=tip
install: |
  set -e
  test x$TRAVIS_OS_NAME = xosx && export CXX=clang++ CC=clang || true # default CC=gcc for `language: c'
  if type -t gvm; then gvm get; else curl -sSL $GVMINSTALLER_URL | bash; fi
  source ~/.gvm/scripts/gvm
  gvm version
  gvm install $GVM_GO --binary # || gvm install $GVM_GO
  gvm use $GVM_GO; gvm list
  cd; mkdir -p gopath/src; mv build gopath/src/github.com; cd gopath/src/github.com/$TRAVIS_REPO_SLUG
  export GOPATH=~/gopath:$GOPATH PATH=~/gopath/bin:$PATH
  go version; go env
  : ::; make init
script: make test all
before_deploy: mv ~/gopath/bin/ostent ~/gopath/bin/$UNAME
after_deploy:  mv ~/gopath/bin/$UNAME ~/gopath/bin/ostent
deploy: #       # ~/gopath/bin/$UNAME deployed
  file: &deployfi ~/gopath/bin/$UNAME
  provider: releases
  api_key:
    secure: >
      EFMPpR2rZkCdlfWuz7bE4ji3/0OL+fgIq+lXJ5SWDUG7aYWVqlLpR1hYXb0yqy8YA2Rg3xvAfPY/sFZvCyUMv0Wx1ZhiVzNvAUduzYFqovvHoYS4nuv0bXWis4YBnx7zJ7uikl5aGAOB8g0L+ofsUAswlDU5M9g9stDG4upWSgw=
  # https://github.com/travis-ci/dpl#github-releases
  on: {tags: true}
  skip_clean: true
