os: [linux, osx]
env:
  - GVM_GO=go1.4 # release
  # travis env has go1.4 preinstalled
  - GVM_GO=tip
language: c
install:
  - test x$TRAVIS_OS_NAME = xosx && export CXX=clang++ CC=clang || true # default CC=gcc
  - curl -sSL https://github.com/moovweb/gvm/raw/master/binscripts/gvm-installer | bash
  - source ~/.gvm/scripts/gvm #; gvm get; gvm update
# - gvm version # below
  - gvm list # test
  - gvm install $GVM_GO --binary || gvm install $GVM_GO
  - gvm list # test
  - gvm use $GVM_GO
  - export GOPATH=$HOME/gopath:$GOPATH PATH=$HOME/gopath/bin:$PATH
  - pwd
# - cd $HOME/gopath/src/github.com/$TRAVIS_REPO_SLUG
  - gvm version
  - go version
  - go env
  - make init
script:
  - make test all # go test then the build

# after_failure: []
# after_success: []
