os: [linux, osx]
env:
  matrix:
    - GVM_GO=go1.4.1 # release
  # - GVM_GO=tip # pre-release
  global:
    - GVMINSTALLER_URL=https://github.com/moovweb/gvm/raw/master/binscripts/gvm-installer
language: c
install:
  - test x$TRAVIS_OS_NAME = xosx && export CXX=clang++ CC=clang || true # default CC=gcc for `language: c'
  - if type -t gvm; then gvm get; else curl -sSL $GVMINSTALLER_URL | bash; fi
  - source ~/.gvm/scripts/gvm
  - gvm version
  - gvm install $GVM_GO --binary # || gvm install $GVM_GO
  - gvm use $GVM_GO; gvm list
  - cd; mkdir -p gopath/src; mv build gopath/src/github.com; cd gopath/src/github.com/$TRAVIS_REPO_SLUG
  - export GOPATH=~/gopath:$GOPATH PATH=~/gopath/bin:$PATH
  - go version; go env
  - make init
script:
  - make test all # go test then the build
