os: [linux, osx]
env:
  matrix:
    - GVM_GO=go1.4 # release
  # - GVM_GO=tip # pre-release
  global:
    - GVMINSTALLER_URL=https://github.com/moovweb/gvm/raw/master/binscripts/gvm-installer
language: c
install:
  - test x$TRAVIS_OS_NAME = xosx && export CXX=clang++ CC=clang || true # default CC=gcc
  - if type gvm; then gvm get; else curl -sSL $GVMINSTALLER_URL; fi
  - source ~/.gvm/scripts/gvm
  - gvm version
  - gvm install $GVM_GO --binary # || gvm install $GVM_GO
  - gvm use $GVM_GO
  - cd; mkdir src; mv build src/github.com
  - cd $HOME/src/github.com/$TRAVIS_REPO_SLUG
  - export GOPATH=$HOME:$GOPATH PATH=$HOME/bin:$PATH
  - go version; go env
  - make init
script:
  - make test all # go test then the build

# after_failure: []
# after_success: []
