# language: go
# go:
#   - release
#   - tip

# install: make init
# script: make test all # go test then the build

language: c
os: [osx]
# os: [linux, osx]

install: [true]
script:
  - curl -sSL https://github.com/moovweb/gvm/raw/master/binscripts/gvm-installer | bash
  - source ~/.gvm/scripts/gvm
  - gvm install go1.4 -B
  - gvm use go1.4
  - test x$TRAVIS_OS_NAME = xosx && export GCC=gcc CC=gcc
  - go env; echo PRINTENV; printenv
  - make init
  - make test all

# after_failure:
#   - cat $HOME/.gvm/logs/go-go1.4-install.log
